// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __fourierin_RcppExports_h__
#define __fourierin_RcppExports_h__

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace fourierin {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("fourierin", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("fourierin", "fourierin_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in fourierin");
            }
        }
    }

    inline arma::cx_vec fourierin_1d_cpp(arma::vec f, double a, double b, double c, double d, double r, double s) {
        typedef SEXP(*Ptr_fourierin_1d_cpp)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_fourierin_1d_cpp p_fourierin_1d_cpp = NULL;
        if (p_fourierin_1d_cpp == NULL) {
            validateSignature("arma::cx_vec(*fourierin_1d_cpp)(arma::vec,double,double,double,double,double,double)");
            p_fourierin_1d_cpp = (Ptr_fourierin_1d_cpp)R_GetCCallable("fourierin", "fourierin_fourierin_1d_cpp");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_fourierin_1d_cpp(Rcpp::wrap(f), Rcpp::wrap(a), Rcpp::wrap(b), Rcpp::wrap(c), Rcpp::wrap(d), Rcpp::wrap(r), Rcpp::wrap(s));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<arma::cx_vec >(__result);
    }

    inline arma::cx_mat fourierin_2d_cpp(arma::mat f, arma::vec a, arma::vec b, arma::vec c, arma::vec d, double r, double s) {
        typedef SEXP(*Ptr_fourierin_2d_cpp)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_fourierin_2d_cpp p_fourierin_2d_cpp = NULL;
        if (p_fourierin_2d_cpp == NULL) {
            validateSignature("arma::cx_mat(*fourierin_2d_cpp)(arma::mat,arma::vec,arma::vec,arma::vec,arma::vec,double,double)");
            p_fourierin_2d_cpp = (Ptr_fourierin_2d_cpp)R_GetCCallable("fourierin", "fourierin_fourierin_2d_cpp");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_fourierin_2d_cpp(Rcpp::wrap(f), Rcpp::wrap(a), Rcpp::wrap(b), Rcpp::wrap(c), Rcpp::wrap(d), Rcpp::wrap(r), Rcpp::wrap(s));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<arma::cx_mat >(__result);
    }

    inline arma::cx_vec fourierin_cx_1d_cpp(arma::cx_vec f, double a, double b, double c, double d, double r, double s) {
        typedef SEXP(*Ptr_fourierin_cx_1d_cpp)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_fourierin_cx_1d_cpp p_fourierin_cx_1d_cpp = NULL;
        if (p_fourierin_cx_1d_cpp == NULL) {
            validateSignature("arma::cx_vec(*fourierin_cx_1d_cpp)(arma::cx_vec,double,double,double,double,double,double)");
            p_fourierin_cx_1d_cpp = (Ptr_fourierin_cx_1d_cpp)R_GetCCallable("fourierin", "fourierin_fourierin_cx_1d_cpp");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_fourierin_cx_1d_cpp(Rcpp::wrap(f), Rcpp::wrap(a), Rcpp::wrap(b), Rcpp::wrap(c), Rcpp::wrap(d), Rcpp::wrap(r), Rcpp::wrap(s));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<arma::cx_vec >(__result);
    }

    inline arma::cx_mat fourierin_cx_2d_cpp(arma::cx_mat f, arma::vec a, arma::vec b, arma::vec c, arma::vec d, double r, double s) {
        typedef SEXP(*Ptr_fourierin_cx_2d_cpp)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_fourierin_cx_2d_cpp p_fourierin_cx_2d_cpp = NULL;
        if (p_fourierin_cx_2d_cpp == NULL) {
            validateSignature("arma::cx_mat(*fourierin_cx_2d_cpp)(arma::cx_mat,arma::vec,arma::vec,arma::vec,arma::vec,double,double)");
            p_fourierin_cx_2d_cpp = (Ptr_fourierin_cx_2d_cpp)R_GetCCallable("fourierin", "fourierin_fourierin_cx_2d_cpp");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_fourierin_cx_2d_cpp(Rcpp::wrap(f), Rcpp::wrap(a), Rcpp::wrap(b), Rcpp::wrap(c), Rcpp::wrap(d), Rcpp::wrap(r), Rcpp::wrap(s));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<arma::cx_mat >(__result);
    }

    inline Rcpp::ComplexVector fft_rcpp(Rcpp::ComplexVector v) {
        typedef SEXP(*Ptr_fft_rcpp)(SEXP);
        static Ptr_fft_rcpp p_fft_rcpp = NULL;
        if (p_fft_rcpp == NULL) {
            validateSignature("Rcpp::ComplexVector(*fft_rcpp)(Rcpp::ComplexVector)");
            p_fft_rcpp = (Ptr_fft_rcpp)R_GetCCallable("fourierin", "fourierin_fft_rcpp");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_fft_rcpp(Rcpp::wrap(v));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<Rcpp::ComplexVector >(__result);
    }

}

#endif // __fourierin_RcppExports_h__
