// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __fourierin_h__
#define __fourierin_h__

#include "fourierin_RcppExports.h"

#endif // __fourierin_h__
