// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ecf_mod_1d
NumericVector ecf_mod_1d(NumericVector t, NumericVector smp);
RcppExport SEXP fourierin_ecf_mod_1d(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type smp(smpSEXP);
    __result = Rcpp::wrap(ecf_mod_1d(t, smp));
    return __result;
END_RCPP
}
// fourierin_1d
arma::cx_vec fourierin_1d(arma::vec f, double a, double b, double c, double d, double r);
RcppExport SEXP fourierin_fourierin_1d(SEXP fSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    __result = Rcpp::wrap(fourierin_1d(f, a, b, c, d, r));
    return __result;
END_RCPP
}
