# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fourierin_1d_cpp <- function(f, a, b, c, d, r, s) {
    .Call('fourierin_fourierin_1d_cpp', PACKAGE = 'fourierin', f, a, b, c, d, r, s)
}

fourierin_1d_nonregular_cpp <- function(f, a, b, w, resolution, r, s) {
    .Call('fourierin_fourierin_1d_nonregular_cpp', PACKAGE = 'fourierin', f, a, b, w, resolution, r, s)
}

fourierin_2d_cpp <- function(f, a, b, c, d, r, s) {
    .Call('fourierin_fourierin_2d_cpp', PACKAGE = 'fourierin', f, a, b, c, d, r, s)
}

fourierin_2d_nonregular_cpp <- function(f, a, b, w, resolution, r, s) {
    .Call('fourierin_fourierin_2d_nonregular_cpp', PACKAGE = 'fourierin', f, a, b, w, resolution, r, s)
}

fourierin_cx_1d_cpp <- function(f, a, b, c, d, r, s) {
    .Call('fourierin_fourierin_cx_1d_cpp', PACKAGE = 'fourierin', f, a, b, c, d, r, s)
}

fourierin_cx_1d_nonregular_cpp <- function(f, a, b, w, resolution, r, s) {
    .Call('fourierin_fourierin_cx_1d_nonregular_cpp', PACKAGE = 'fourierin', f, a, b, w, resolution, r, s)
}

fourierin_cx_2d_cpp <- function(f, a, b, c, d, r, s) {
    .Call('fourierin_fourierin_cx_2d_cpp', PACKAGE = 'fourierin', f, a, b, c, d, r, s)
}

#' @export
fft_rcpp <- function(real, imag) {
    .Call('fourierin_fft_rcpp', PACKAGE = 'fourierin', real, imag)
}

#' @export
fft_rcpp_2 <- function(v) {
    .Call('fourierin_fft_rcpp_2', PACKAGE = 'fourierin', v)
}

#' @export
fft_rcpp_3 <- function(v) {
    .Call('fourierin_fft_rcpp_3', PACKAGE = 'fourierin', v)
}

#' @export
fft_rcpp_4 <- function(v) {
    .Call('fourierin_fft_rcpp_4', PACKAGE = 'fourierin', v)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('fourierin_RcppExport_registerCCallable', PACKAGE = 'fourierin')
})
