# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Module of the empirical characteristic function
#'
#' It computes the module of the empirical characteristic function
#' evaluated on a sample
#' @export
ecf_mod_1d <- function(t, smp) {
    .Call('fourierin_ecf_mod_1d', PACKAGE = 'fourierin', t, smp)
}

fourierin_1d_cpp <- function(f, a, b, c, d, r, s) {
    .Call('fourierin_fourierin_1d_cpp', PACKAGE = 'fourierin', f, a, b, c, d, r, s)
}

fourierin_2d_cpp <- function(f, a, b, c, d, r, s) {
    .Call('fourierin_fourierin_2d_cpp', PACKAGE = 'fourierin', f, a, b, c, d, r, s)
}

