# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Module of the empirical characteristic function
#'
#' It computes the module of the empirical characteristic function
#' evaluated on a sample
#' @export
ecf_mod <- function(t, smp) {
    .Call('fourierin_ecf_mod', PACKAGE = 'fourierin', t, smp)
}

